"""create events table

Revision ID: d0bb8655dd7d
Revises:
Create Date: 2026-10-08 00:53:02.327462
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d0bb8655dd7d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=True),
        sa.Column("service", sa.Text(), nullable=False),
        sa.Column("event_name", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=True),
        sa.Column("read_only", sa.Boolean(), nullable=True),
        sa.Column("region", sa.Text(), nullable=False),
        sa.Column("principal_type", sa.String(length=32), nullable=False),
        sa.Column("principal", sa.Text(), nullable=True),
        sa.Column("principal_arn", sa.Text(), nullable=True),
        sa.Column("session_name", sa.Text(), nullable=True),
        sa.Column("access_key_id", sa.Text(), nullable=True),
        sa.Column("mfa_authenticated", sa.Boolean(), nullable=True),
        sa.Column("source_address", sa.Text(), nullable=True),
        sa.Column("source_ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("request_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_event", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_events_event_id")),
    )
    op.create_index(op.f("ix_events_event_name"), "events", ["event_name"], unique=False)
    op.create_index(op.f("ix_events_principal_arn"), "events", ["principal_arn"], unique=False)
    op.create_index(op.f("ix_events_timestamp"), "events", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_timestamp"), table_name="events")
    op.drop_index(op.f("ix_events_principal_arn"), table_name="events")
    op.drop_index(op.f("ix_events_event_name"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
