"""create findings tables

Revision ID: 5bd6b98c7438
Revises: d0bb8655dd7d
Create Date: 2026-10-10 21:24:39.644782
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5bd6b98c7438"
down_revision: str | Sequence[str] | None = "d0bb8655dd7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "findings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("finding_id", sa.Text(), nullable=False),
        sa.Column("detector_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=True),
        sa.Column("principal", sa.Text(), nullable=True),
        sa.Column("principal_arn", sa.Text(), nullable=True),
        sa.Column("resource", sa.Text(), nullable=True),
        sa.Column("risk_score", sa.SmallInteger(), nullable=False),
        sa.Column("risk_factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('informational', 'low', 'medium', 'high', 'critical')",
            name=op.f("ck_findings_severity"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'acknowledged', 'resolved', 'false_positive')",
            name=op.f("ck_findings_status"),
        ),
        sa.CheckConstraint("last_seen >= first_seen", name=op.f("ck_findings_time_range")),
        sa.CheckConstraint("risk_score BETWEEN 0 AND 100", name=op.f("ck_findings_risk_score")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint("finding_id", name=op.f("uq_findings_finding_id")),
    )
    op.create_index(op.f("ix_findings_detector_id"), "findings", ["detector_id"], unique=False)
    op.create_index(op.f("ix_findings_first_seen"), "findings", ["first_seen"], unique=False)
    op.create_index(op.f("ix_findings_principal_arn"), "findings", ["principal_arn"], unique=False)
    op.create_index(op.f("ix_findings_risk_score"), "findings", ["risk_score"], unique=False)
    op.create_table(
        "finding_events",
        sa.Column("finding_id", sa.Text(), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_finding_events_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.finding_id"],
            name=op.f("fk_finding_events_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("finding_id", "event_id", name=op.f("pk_finding_events")),
    )
    op.create_index(
        op.f("ix_finding_events_event_id"), "finding_events", ["event_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_finding_events_event_id"), table_name="finding_events")
    op.drop_table("finding_events")
    op.drop_index(op.f("ix_findings_risk_score"), table_name="findings")
    op.drop_index(op.f("ix_findings_principal_arn"), table_name="findings")
    op.drop_index(op.f("ix_findings_first_seen"), table_name="findings")
    op.drop_index(op.f("ix_findings_detector_id"), table_name="findings")
    op.drop_table("findings")
    # ### end Alembic commands ###
